### ISSUE TITLE
Add click for close window error

### ISSUE THREAD

**Issue by orb666** [SmartBotBlack/farmers-world-bot#1]
Can you please add command to close if there is an error in CPU and also the other error that pop-up. It has been appearing randomly in-game even if you did not use trade that causes your cpu to get high.

**Comment by GIPPERMORF** [comment]
поддерживаю комментатора выше, Если бы включил эту ошибку в пул, было бы отлично

**Comment by voodee** [comment]
@orb666 @GIPPERMORF 
An update came out today. The bug was fixed.
