### ISSUE TITLE
Can this script be run from a third-party application?

### ISSUE THREAD

**Issue by kevinfredrick** [SmartBotBlack/farmers-world-bot#2]
Hi and thanks for the script

Let's say I want to run this script from a C# WinFoms application or maybe other ways instead of using the browser console, 
I wonder if we can do this, any suggestion would be appreciated to get it run this way.
Another thing, does this script do auto mining, that is, clicking on the countdown button after the counter reaches 00.00.00 for the the saw, axe, fishing rod and etc?

Looking forward to your response.

Keep the bot up and thanks again

**Comment by voodee** [comment]
Hello!
Yes, this script can be run in different ways. Can you tell me which problem you are solving? And why do you need to do it?

**Comment by Daringbaaz** [comment]
> Hello! Yes, this script can be run in different ways. Can you tell me which problem you are solving? And why do you need to do it?

Maybe he don't wanna put script on console, Developers team may detect open console and scripting,

It Will Be Better If actions can be done through some Chrome extension,

**Comment by voodee** [comment]
Some things are hard to do as a simple script. Our paid script fully emulates the browser and mouse cursor.
