### ISSUE TITLE
Universal Code Generator

### ISSUE THREAD

**Issue by Daringbaaz** [SmartBotBlack/farmers-world-bot#4]
Hi, Please Make a Code Generator Which has the option to Select Maps/Exclude Map,
Where We Can Set OwnDelays Time / Waiting time.

This Way in case if anyone Don't Wanna Mine or Feed any Animals (Map) Then it Will Be Great for those users.

Like I Have Chicken But I Don't Wanna Feed or I Wanna Exclude Chicken Map For Checking or Clicking.

Thankss

**Comment by voodee** [comment]
Thank you for the suggested functionality. It is implemented in the new version.

Now you can select the necessary maps for mining in the script settings.

```
  // Maps on which you can collect resources
  // 1 — Mining
  // 2 — Chiken
  // 3 — Plant
  // 4 — Cow
  const availableMaps = [1, 2, 3, 4];
```
