### ISSUE TITLE
Locked With Specific Map

### ISSUE THREAD

**Issue by Daringbaaz** [SmartBotBlack/farmers-world-bot#7]
Hey, I Really Appreciate your Last Update, Which Has the option to Exclude maps, It Will Be Very Helpful for those Who Have Multiple Maps,

Can You Make Something Which Has also option to Locked Map,

: Like I Have only Mining tools or Someone Have only Farming Tools, 
In That Case, No Need to Keep opening Map and Selecting Map Again and Again.

: I Had Monitor That When We Change Map, it's Request all Images from Farmersworld Server, it's Means Lot's of Request From the Same IP, and it's Keep Requesting When Script Switch Map.

To Avoid Multiple Requests We Can open Different Browsers/Profile Based on Map and locked With Map ID,

So Script Will Check Countdown and only Hit Necessary Request, It's Means No Need to Keep Downloading all Resources and We Can Reduce Lot's of Request,

I Think It Will Be Better and Safe

**Comment by voodee** [comment]
Some things are hard to do as a simple script. In our paid version, we have more options for emulating human actions. The cloud version is more secure.
