### ISSUE TITLE
Unable to open Pop Up

### ISSUE THREAD

**Issue by Beardinthewild** [SmartBotBlack/farmers-world-bot#8]
Sometimes a popup will appear saying "unable to open pop up" and this halts that particular item from being mined is there a way to add in that it checks for this as well as the needs resources pop up?

**Comment by Daringbaaz** [comment]
You Need to Whitelist Domain on Your Browser to Allow Popup,

**Comment by voodee** [comment]
@Beardinthewild 
We have analyzed this problem using another bot as an example. Check video https://youtu.be/rYehqByJPHs?t=68
